- hosts: all
  #connection: local
  gather_facts: no
 
  become: yes
  vars:
    LOCAL_HOME: "{{ lookup('env','HOME')}}"

  tasks:
  - name: Collect only facts returned by facter to save time
    setup:
      gather_subset:
         - '!all'
         - '!any'
         - facter

  - name: Install wget package
    shell: |
         sudo apt install -y wget
    when: ansible_os_family == 'Debian'

  - name: Install wget package on amazon linux(redhat)
    shell: |
         yum install -y wget
    when: (ansible_os_family == 'RedHat') and (ansible_distribution == 'Amazon')

    #- meta: end_play

  - name: Install jenkins from repo
    shell: |
          wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
          sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
          sudo apt-get -y update
          sudo apt-get -y install jenkins
    register: RESULT          
    when: ansible_os_family == 'Debian'

  - debug:
       var: RESULT

  - name: Install jenkins from repo onto amazon linux
    shell: |
          yum -y install java-1.8.0-openjdk.x86_64
          wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
          rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
          yum -y update
          yum -y install jenkins java
    register: RESULT          
    when: (ansible_os_family == 'RedHat') and (ansible_distribution == 'Amazon')

  - debug:
       var: RESULT
