---
- hosts: localhost
  #connection: local
  gather_facts: no

  vars:
    REGION: 'ap-northeast-2'
    LOCAL_HOME: "{{ lookup('env','HOME')}}"
    VPC_ID: 'vpc-f51eca9e'
    #STATE: absent
    STATE: present
    INSTCNT: 1
    ZN: 'ap-northeast-2c'
    #ansible_pass: test@kkk2020
    #ansible_user: administrator
    #ansible_password: "{{ ansible_pass }}"
    #ansible_host: 13.125.248.231
    #ansible_connection: winrm
    #ansible_winrm_transport: basic
    #ansible_winrm_server_cert_validation: ignore

  tasks:

   - ec2_instance_info:
        filters:
                #instance-state-name: [ "running", "stopping", "stopped" ]
            instance-state-name: [ "running" ]
     register: out


   - debug:
           # var: out.instances[0].private_ip_address
        var: out
            #- out




  
#  - name: Grant domain account the SeServiceLogonRight user right
#    win_user_right:
#      name: SeServiceLogonRight
#      users:
#        - tomcat
#      action: add
#
#  - name: tomcat service start
#    win_service:
#      desktop_interact: no
#      force_dependent_services: yes
#      name: Tomcat8
#      start_mode: auto
#      state: started
#      #state: stopped
#      #username: administrator
#      username: tomcat
#      #username: LocalSystem
#      #password: Pass#G*#9087
#      #password: "{{ ansible_pass }}"
#      password: ''

  #tomcat_start
  #- name: tomcat start shell execute
  #  win_shell: 'tomcat8 //IS//Tomcat8 /user tomcat --DisplayName="Apache Tomcat 8" \
  #    --Install="C:\tomcat8\bin\tomcat8.exe" --Jvm=auto \
  #    --StartMode=jvm --StopMode=jvm \
  #    --StartClass=org.apache.catalina.startup.Bootstrap --StartParams=start \
  #    --StopClass=org.apache.catalina.startup.Bootstrap --StopParams=stop'
  #
  #  with_items: "{{ ec2_out.instances }}"
  #  register: tomcat8_start
