---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    REGION: 'ap-northeast-2'
    SSH_KEY_NAME: 'win_instance_key'
    LOCAL_HOME: "{{ lookup('env','HOME')}}"
    VPC_ID: 'vpc-f51eca9e'
    #STATE: absent
    STATE: present
    INSTCNT: 1
    ZN: 'ap-northeast-2c'
  tasks:

   #- ec2_instance_facts:
   #- ec2_instance_info: <after ansible 2.9.0>
   - ec2_instance_info:
       filters:
         "tag:name": winwastst
         instance-state-name: ["running"]
         #"Status Check" : ok
     register: result

   - debug:
           #var: result.instances[0]['public_ip_address']
          var: result.instances[0]
           #var: result
           
   - name: get the Administrator password
     ec2_win_password:
      profile: default
      instance_id: "{{ result.instances[0]['instance_id'] }}"
      region: ap-northeast-2
      key_file: "win_instance_key.pem"
     register: adminpass

   - debug:
        var: adminpass

   - name: nc to win host 3389 if it is ready or not
     command: "/bin/nc -zv {{ result.instances[0]['public_ip_address'] }} 3389" 
     #command: "echo {{ result.instances[0]['public_ip_address'] }}"
     register: result

   - debug:
       var: result
